base_url = "https://zola-mikoto.netlify.com"
title = "mikoto theme"
description = ""
compile_sass = true
slugify-path = true
highlight_code = true
highlight_theme = "monokai"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    # {name = "series", rss = true},
]



# theme = "mikoto"
extra_syntaxes = ["syntaxes"]



[extra]
author = "Aster"
mikoto_title = "Mikoto"
mikoto_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    # {url = "$BASE_URL/series", name = "Series"},
    {url = "$BASE_URL/about", name = "About"},
]

favicon = "https://avatars.githubusercontent.com/u/43047029"
github_link = "https://github.com/GalAster/zola-theme-mikoto"

# comment `enable` to close the plugin

aplayer_enable = true
aplayer_background = true
aplayer_background_autolink = "http://music.163.com/playlist?id=2964675527"
aplayer_background_autoplay = false

live2d_enable = true

mathjax_enable = true
katex_enalbe = true

